"""Db migration

Revision ID: 933f3030e2cf
Revises: 
Create Date: 2024-05-26 13:14:38.059004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '933f3030e2cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_locations_id', table_name='asset_locations')
    op.drop_index('ix_asset_locations_latitude', table_name='asset_locations')
    op.drop_index('ix_asset_locations_longitude', table_name='asset_locations')
    op.drop_table('asset_locations')
    op.drop_index('ix_contact_sales_call_time', table_name='contact_sales')
    op.drop_index('ix_contact_sales_id', table_name='contact_sales')
    op.drop_index('ix_contact_sales_phone_number', table_name='contact_sales')
    op.drop_index('ix_contact_sales_status', table_name='contact_sales')
    op.drop_table('contact_sales')
    op.drop_index('ix_user_organisation_assignments_id', table_name='user_organisation_assignments')
    op.drop_table('user_organisation_assignments')
    op.drop_index('ix_organisation_contacts_country', table_name='organisation_contacts')
    op.drop_index('ix_organisation_contacts_first_name', table_name='organisation_contacts')
    op.drop_index('ix_organisation_contacts_id', table_name='organisation_contacts')
    op.drop_index('ix_organisation_contacts_last_name', table_name='organisation_contacts')
    op.drop_index('ix_organisation_contacts_message', table_name='organisation_contacts')
    op.drop_index('ix_organisation_contacts_role', table_name='organisation_contacts')
    op.drop_table('organisation_contacts')
    op.drop_index('ix_business_profiles_business_address', table_name='business_profiles')
    op.drop_index('ix_business_profiles_business_email', table_name='business_profiles')
    op.drop_index('ix_business_profiles_business_location', table_name='business_profiles')
    op.drop_index('ix_business_profiles_business_logo', table_name='business_profiles')
    op.drop_index('ix_business_profiles_business_name', table_name='business_profiles')
    op.drop_index('ix_business_profiles_business_phone', table_name='business_profiles')
    op.drop_index('ix_business_profiles_id', table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index('ix_features_feature_description', table_name='features')
    op.drop_index('ix_features_feature_name', table_name='features')
    op.drop_index('ix_features_icon_url', table_name='features')
    op.drop_index('ix_features_id', table_name='features')
    op.drop_index('ix_features_status', table_name='features')
    op.drop_table('features')
    op.drop_index('ix_package_item_assignments_id', table_name='package_item_assignments')
    op.drop_table('package_item_assignments')
    op.drop_index('ix_marker_icons_icon_name', table_name='marker_icons')
    op.drop_index('ix_marker_icons_icon_url', table_name='marker_icons')
    op.drop_index('ix_marker_icons_id', table_name='marker_icons')
    op.drop_index('ix_marker_icons_status', table_name='marker_icons')
    op.drop_table('marker_icons')
    op.drop_table('token')
    op.drop_index('ix_package_items_id', table_name='package_items')
    op.drop_index('ix_package_items_item_name', table_name='package_items')
    op.drop_index('ix_package_items_status', table_name='package_items')
    op.drop_table('package_items')
    op.drop_index('ix_Facilitators_account_type', table_name='Facilitators')
    op.drop_index('ix_Facilitators_email_address', table_name='Facilitators')
    op.drop_index('ix_Facilitators_first_name', table_name='Facilitators')
    op.drop_index('ix_Facilitators_id', table_name='Facilitators')
    op.drop_index('ix_Facilitators_last_name', table_name='Facilitators')
    op.drop_index('ix_Facilitators_phone_number', table_name='Facilitators')
    op.drop_index('ix_Facilitators_school', table_name='Facilitators')
    op.drop_index('ix_Facilitators_verifiedAt', table_name='Facilitators')
    op.drop_table('Facilitators')
    op.drop_index('ix_assets_asset_name', table_name='assets')
    op.drop_index('ix_assets_asset_status', table_name='assets')
    op.drop_index('ix_assets_id', table_name='assets')
    op.drop_index('ix_assets_marker_color', table_name='assets')
    op.drop_index('ix_assets_vin_no', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_onboardings_id', table_name='onboardings')
    op.drop_index('ix_onboardings_number_of_assets', table_name='onboardings')
    op.drop_index('ix_onboardings_number_of_months', table_name='onboardings')
    op.drop_index('ix_onboardings_onboarding_type', table_name='onboardings')
    op.drop_table('onboardings')
    op.drop_index('ix_packages_id', table_name='packages')
    op.drop_index('ix_packages_package_description', table_name='packages')
    op.drop_index('ix_packages_package_name', table_name='packages')
    op.drop_index('ix_packages_package_price', table_name='packages')
    op.drop_table('packages')
    op.drop_index('ix_onboarding_feature_assignments_id', table_name='onboarding_feature_assignments')
    op.drop_table('onboarding_feature_assignments')
    op.drop_index('ix_asset_types_asset_type_name', table_name='asset_types')
    op.drop_index('ix_asset_types_description', table_name='asset_types')
    op.drop_index('ix_asset_types_icon_url', table_name='asset_types')
    op.drop_index('ix_asset_types_id', table_name='asset_types')
    op.drop_index('ix_asset_types_status', table_name='asset_types')
    op.drop_table('asset_types')
    op.drop_index('ix_equipment_types_equipment_type_name', table_name='equipment_types')
    op.drop_index('ix_equipment_types_id', table_name='equipment_types')
    op.drop_index('ix_equipment_types_status', table_name='equipment_types')
    op.drop_table('equipment_types')
    op.drop_table('email_verifications')
    op.drop_index('ix_users_account_type', table_name='users')
    op.drop_index('ix_users_address', table_name='users')
    op.drop_index('ix_users_email_address', table_name='users')
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.drop_index('ix_users_location', table_name='users')
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_index('ix_users_verifiedAt', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Facilitators',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('verifiedAt', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('school', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_profile_uuid'], ['business_profiles.uuid'], name='users_business_profile_uuid_fkey'),
    sa.PrimaryKeyConstraint('id', 'uuid', name='users_pkey'),
    sa.UniqueConstraint('uuid', name='users_uuid_key'),
    postgresql_ignore_search_path=False
    )
  
  
    op.create_index('ix_Facilitators_verifiedAt', 'Facilitators', ['verifiedAt'], unique=False)
    op.create_index('ix_Facilitators_school', 'Facilitators', ['school'], unique=False)
    op.create_index('ix_Facilitators_phone_number', 'Facilitators', ['phone_number'], unique=False)
    op.create_index('ix_Facilitators_last_name', 'Facilitators', ['last_name'], unique=False)
    op.create_index('ix_Facilitators_id', 'Facilitators', ['id'], unique=False)
    op.create_index('ix_Facilitators_first_name', 'Facilitators', ['first_name'], unique=False)
    op.create_index('ix_Facilitators_email_address', 'Facilitators', ['email_address'], unique=False)
    op.create_index('ix_Facilitators_account_type', 'Facilitators', ['account_type'], unique=False)
    op.create_table('package_items',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('package_items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'uuid', name='package_items_pkey'),
    sa.UniqueConstraint('uuid', name='package_items_uuid_key'),
    postgresql_ignore_search_path=False
    )

  
    # ### end Alembic commands ###
