const contest_40_2 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Corona viruses run helter skelter when they see or smell me from afar.\nI can travel abroad through the Kotoka Airport a hundred times in a month and I am confident I shall never test positive for COVID-19.\nYou may have met me before, at a market or school and never recognized me.\nI appeared white to you then because I was in the form of an aqueous aerosol\nI am obviously not a living organism, but a gaseous chemical element used in preparing a solution to eliminate microorganisms.\nWho am I?",
        "Question has figure": "No",
        "clue1": "Corona viruses run helter skelter when they see or smell me from afar.",
        "clue2": "I can travel abroad through the Kotoka Airport a hundred times in a month and I am confident I shall never test positive for COVID-19.",
        "clue3": "You may have met me before, at a market or school and never recognized me.",
        "clue4": "I appeared white to you then because I was in the form of an aqueous aerosol",
        "clue5": "I am obviously not a living organism, but a gaseous chemical element used in preparing a solution to eliminate microorganisms.Who am I?",
        "clue_nums": 5,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Chlorine gas (Do not accept Chlorine or Chlorine solution)",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Opponent_Answer": 3,
        "Topic Tag": ["Chemical Elements", "Disinfection"]
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I may be a number or a polynomial.\nAs a polynomial an example of me is $f(x)=(x+2)(x-3)$\nAs a number, an example of me is 6.\nI am characterized by having proper factors.\nI am also a purposely designed engineering material created by combining single materials to produce a structural property not present in the single materials used.\nAn example in this context is fiberglass.\nWho am I?",
        "Question has figure": "No",
        "clue1": "I may be a number or a polynomial",
        "clue2": "nAs a polynomial an example of me is $f(x)=(x+2)(x-3)$",
        "clue3": "As a number, an example of me is 6.",
        "clue4": "I am characterized by having proper factors",
        "clue5": "I am also a purposely designed engineering material created by combining single materials to produce a structural property not present in the single materials used. An example in this context is fiberglass.\nWho am I",
        "clue_nums": 5,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "COMPOSITE",
        "calculations present": "No",
        "Subject": "Mathematics",
        "Opponent_Answer": 3,
        "Topic Tag": ["Polynomials", "Materials Science"]
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am normally used to refer to a white or coloured circle or a set of concentric circles of light seen around a luminous body\nIn anatomy, I am a part of the body resembling or likened to a crown.\nIn astronomy, I am a faintly luminous envelope outside of the sun's chromosphere\nIn botany, I am a ring of tissue arising from the corolla or perianth of a flower and standing between the perianth lobes and the stamens.\nThanks to COVID-19, I have now become a household name.\nWHO AM I?",
        "Question has figure": "No",
        "clue1": "I am normally used to refer to a white or coloured circle or a set of concentric circles of light seen around a luminous body",
        "clue2": "In anatomy, I am a part of the body resembling or likened to a crown",
        "clue3": "In astronomy, I am a faintly luminous envelope outside of the sun's chromosphere",
        "clue4": "In botany, I am a ring of tissue arising from the corolla or perianth of a flower and standing between the perianth lobes and the stamens.",
        "clue5": "Thanks to COVID-19, I have now become a household name. WHO AM I?",
        "clue_nums": 5,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Corona",
        "calculations present": "No",
        "Subject": "Biology",
        "Opponent_Answer": 3,
        "Topic Tag": ["Astronomy", "Biology"]
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "My name suggests I am an assembly of a definite number of parts.\nThe number $6.62607015 \\times 10^{-34}$ is very important to me.\nI used to be based on water.\nI later came to be derived from an artefact whose permanent home is in a northern latitude.\nI have now shed all my relics in full embrace of Planck.\nWho am I?",
        "Question has figure": "No",
        "clue1": "My name suggests I am an assembly of a definite number of parts",
        "clue2": "The number $6.62607015 \\times 10^{-34}$ is very important to me.",
        "clue3": "I used to be based on water.",
        "clue4": "I later came to be derived from an artefact whose permanent home is in a northern latitude.",
        "clue5": "I have now shed all my relics in full embrace of Planck.\nWho am I?",
        "clue_nums": 5,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Kilogram",
        "calculations present": "No",
        "Subject": "Physics",
        "Opponent_Answer": 0,
        "Topic Tag": ["Units of Measurement", "Physics"]
    }
]

export default contest_40_2