const contest_40_2 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "What is the temperature associated with the cosmic microwave background radiation and what is the wavelength at which it is most intense?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$2.72 \\mathrm{~K}, 1.06 \\mathrm{~mm}$",
        "calculations present": "Yes",
        "Subject": "Physics",
        "Topic Tag": ["Cosmic Microwave Background", "Astrophysics"]
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Is the sun a blackbody? Why or why not?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "It is not; it is not in thermal equilibrium",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Blackbody Radiation", "Physics"]
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Why is it essential that blood pressure in the capillary vessels be much lower than that in the artery?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Low blood pressure in the capillaries slows blood down the flow of blood, so it gives enough time for diffusion of substances between the blood and cells. The walls of capillaries are also much thinner than those of arteries (squamous epithelium only), so they could rupture / break if the blood pressure is too high in them.",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Circulatory System", "Biology"]
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Why should a person who is feeling dizzy be fed with glucose or a fruit juice instead of a bread and margarine that might give more energy?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Glucose gives instant energy as it is absorbed and reaches the blood. Bread and margarine, however, requires time to digest and be absorbed. As sick people need immediate energy supply, they are fed with glucose or given fruit juice.",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Metabolism", "Biology"]
    },
    {
        "S/N": 5,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Why should mowing lawn grass facilitate better maintenance?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Apical dominance of terminal bud is due to the secretion of auxin (IA.A) by apical bud. Hence the removal of apical bud causes sprouting of lateral buds with stimulation of intercalary meristem thereby facilitating better maintenance of grass.",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Metabolism", "Biology"]
    },
    {
        "S/N": 6,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Calculate the mass of aluminium that can be obtained from electrolysis of molten aluminium oxide after passing a charge of 82.0 Faraday. $\\mathrm{Al}=27.0$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "738 grams",
        "calculations present": "Yes",
        "Subject": "Chemistry",
        "Topic Tag": ["Electrolysis", "Chemistry"]
    },
    {
        "S/N": 7,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "What is the catalyst used in the Haber Process?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "A mixture of metallic iron and aluminium oxide.\n(Accept a mixture of metallic iron and various oxides)",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Industrial Processes", "Chemistry"]
    },
    {
        "S/N": 8,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Give the systematic name of any pentanal containing 6 carbons.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Any one of:\n2-Methylpentanal; 3-Methylpentanal; $\\quad$ 4-Methylpentanal",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Organic Chemistry", "Nomenclature"]
    },
    {
        "S/N": 9,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "A fair coin and a fair die are tossed once. Find the probability of obtaining a head and a number greater than 3 , or a tail and a number less than 4 .",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "1/2",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Organic Chemistry", "Nomenclature"]
    },
    {
        "S/N": 10,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Find the equation for the function $\\mathrm{g}(\\mathrm{x})$ which is obtained after the graph of the function $\\mathrm{y}=2 \\mathrm{x}$ is reflected in the line $\\mathrm{y}=\\mathrm{x}$ and translated 2 units to the right.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$g(x)=1 / 2(x-2)$ or $g(x)=1 / 2 x-1$\n[reflect in $\\mathrm{y}=\\mathrm{x}$ gives $\\mathrm{x}=2 \\mathrm{y}$ or $\\mathrm{y}=(1 / 2) \\mathrm{x}, 2$ units right gives $\\mathrm{y}=(1 / 2)(\\mathrm{x}-2)$ ]",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Functions", "Mathematics"]
    }
]

export default contest_40_2