const contest_40_1 = [
    {
        "S/N": 1,
        "Has Preamble": "Yes",
        "Preamble Text": "Provide suitable explanations for the following:",
        "Question": "Why should wilted leaves of lettuce become crispy/firm when placed in cold water for a while?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Wilted lettuce leaves when placed in cold water for a while absorb water through endosmosis, the cells of leaves became turgid and thus become crispy/firm.",
        "calculations present": "No",
        "Subject": "Biology",
        "Opponent_Answer": 2,
        "Topic Tag": ["Osmosis", "Plant Physiology"]
    },
    {
        "S/N": 2,
        "Has Preamble": "Yes",
        "Preamble Text": "Provide suitable explanations for the following:",
        "Question": "Why do the leaves of some plants roll up on a bright sunny day?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "The rate of transpiration is high on bright sunny gays. As a result, the plants roll up their leaves so as to reduce the exposed surface area to the sun and thus the rate of transpiration./ as well as the stomata get covered and water loss through stomata can be reduced.",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Transpiration", "Plant Physiology"]
    },
    {
        "S/N": 3,
        "Has Preamble": "Yes",
        "Preamble Text": "Give the features of saliva that allows it to perform the following functions.",
        "Question": "It serves as a buffer.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Saliva has a high concentration of bicarbonate ions that allows it to act as physiological buffer",
        "calculations present": "No",
        "Subject": "Biology",
        "Opponent_Answer": 2,
        "Topic Tag": ["Saliva", "Biochemistry"]
    },
    {
        "S/N": 4,
        "Has Preamble": "Yes",
        "Preamble Text": "Give the features of saliva that allows it to perform the following functions.",
        "Question": "It helps in mineralization of the teeth",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Saliva contains high concentration of calcium and phosphate, which helps in mineralization of teeth.",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Saliva", "Biochemistry"]
    },
    {
        "S/N": 5,
        "Has Preamble": "Yes",
        "Preamble Text": "State the effect(s) of each of the following on biodiversity the variability among living organisms from all source.",
        "Question": "Habitat loss",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Habitat loss will decrease biodiversity. When this occurs only the animals that are able to adapt and live within the new habitat will survive. This could potentially cause a genetic bottleneck for those that were once thriving in the initial habitat.",
        "calculations present": "No",
        "Subject": "Biology",
        "Opponent_Answer": 2,
        "Topic Tag": ["Biodiversity", "Ecology"]
    },
    {
        "S/N": 6,
        "Has Preamble": "Yes",
        "Preamble Text": "State the effect(s) of each of the following on biodiversity the variability among living organisms from all source.",
        "Question": "Overharvesting",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Overharvesting can limit biodiversity. If too much of a species (whether plants or animals) is harvested for human use, then there is the potential that certain genes from the pool are completely wiped out. This means that they will be very hard to re-introduce into the population, and the biodiversity lessens.",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Biodiversity", "Ecology"]
    },
    {
        "S/N": 7,
        "Has Preamble": "Yes",
        "Preamble Text": "Each school will be presented with an element. You are to state i) the symbol, ii) the word and the language from which the symbol is derived.",
        "Question": "Lead.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Symbol $\\mathrm{Pb} ; \\quad$ Word Plumbum; $\\quad$ Language Latin.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Opponent_Answer": 3,
        "Topic Tag": ["Chemical Symbols", "Chemistry"]
    },
    {
        "S/N": 8,
        "Has Preamble": "Yes",
        "Preamble Text": "Each school will be presented with an element. You are to state i) the symbol, ii) the word and the language from which the symbol is derived.",
        "Question": "Mercury.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Symbol Hg; Word Hydrargyrum; Language Latin.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Chemical Symbols", "Chemistry"]
    },
    {
        "S/N": 9,
        "Has Preamble": "Yes",
        "Preamble Text": "Each school will be presented with a reagent. Name the group of natural products for which the reagent is used for testing and state the expected observation for positive result.",
        "Question": "Tollens' Reagent.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Reducing sugars Expected Positive result: $\\quad$ Silver mirror/metal.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Opponent_Answer": 1,
        "Topic Tag": ["Chemical Reagents", "Chemistry"]
    },
    {
        "S/N": 10,
        "Has Preamble": "Yes",
        "Preamble Text": "Each school will be presented with a reagent. Name the group of natural products for which the reagent is used for testing and state the expected observation for positive result.",
        "Question": "Ninhydrin.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Proteins (and 2-amino acids)\nExpected Positive results: Purple colouration",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Chemical Reagents", "Chemistry"]
    },
    // {
    //     "S/N": 11,
    //     "Has Preamble": "Yes",
    //     "Preamble Text": "Phosphorus (V) chloride decomposes to phosphorus (III) chloride and chlorine gas when heated. The balanced equation is as follows:\n$$\n\\mathrm{PCl}_{5(\\mathrm{~g})} \\rightleftharpoons \\mathrm{PCl}_{3(\\mathrm{~g})}+\\mathrm{Cl}_{2(\\mathrm{~g})}\n$$\nThe equilibrium constant $\\mathrm{K}_{\\mathrm{C}}$ for the reaction is 0.0360 at $300{ }^{\\circ} \\mathrm{C}$.",
    //     "Question": "In an experiment when only $20.0 \\%$ of the initial amount of $0.100 \\mathrm{moldm}^{-3}$ of the $\\mathrm{PCl}_{5}$ had decomposed, it was not certain if equilibrium had been attained. If the initial concentration of each of $\\mathrm{PCl}_{3}$ and $\\mathrm{Cl}_{2}$ was zero moldm ${ }^{-3}$, determine by calculating the Reaction Quotient if there was equilibrium. If not state, the direction the reaction should move to establish equilibrium.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "$\\quad \\mathrm{PCl}_{5(\\mathrm{~g})} \\rightleftharpoons \\mathrm{PCl}_{3(\\mathrm{~g})}+\\mathrm{Cl}_{2(\\mathrm{~g})}$\nInitial: $0.100 \\quad 0 \\quad 0$\nFinal: $0.0800 \\quad 0.0200$\n$\\mathrm{Q}=\\frac{(0.0200)^{2}}{(0.0800)}=\\frac{4.00 * 10^{-4}}{8.00 * 10^{-2}}=5.00^{*} 10^{-3}$ or 0.00500\nThis is less than the $\\mathrm{K}_{\\mathrm{C}}\\left(3.60^{*} 10^{-2}\\right)$ and so the reaction is not at equilibrium.\nIt must shift from left to right to reach equilibrium.",
    //     "calculations present": "Yes",
    //     "Subject": "Chemistry",
    //     "Opponent_Answer": 1,
    //     "Topic Tag": ["Chemical Equilibrium", "Chemistry"]
    // },
    // {
    //     "S/N": 12,
    //     "Has Preamble": "Yes",
    //     "Preamble Text": "Phosphorus (V) chloride decomposes to phosphorus (III) chloride and chlorine gas when heated. The balanced equation is as follows:\n$$\n\\mathrm{PCl}_{5(\\mathrm{~g})} \\rightleftharpoons \\mathrm{PCl}_{3(\\mathrm{~g})}+\\mathrm{Cl}_{2(\\mathrm{~g})}\n$$\nThe equilibrium constant $\\mathrm{K}_{\\mathrm{C}}$ for the reaction is 0.0360 at $300{ }^{\\circ} \\mathrm{C}$.",
    //     "Question": "In another experiment $50.0 \\%$ of the initial $0.100 \\mathrm{moldm}^{-3} \\mathrm{PCl}_{5}$ had decomposed. Again, the initial concentration of $\\mathrm{PCl}_{3}$ and $\\mathrm{Cl}_{2}$ was zero moldm equilibrium. If not state, the direction in which the reaction should move to establish equilibrium.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "$\\quad \\mathrm{PCl}_{5(\\mathrm{~g})} \\rightleftharpoons \\mathrm{PCl}_{3(\\mathrm{~g})}+\\mathrm{Cl}_{2(\\mathrm{~g})}$\n$$\n\\begin{aligned}\n& \\begin{array}{llll}\n\\text { Final: } & 0.0500 & 0.0500 & 0.0500\n\\end{array} \\\\\n& \\mathrm{Q}=\\frac{(0.0500)^{2}}{(0.0500)}=0.0500=5.00^{*} 10^{-2} \\text { or } 0.0500\n\\end{aligned}\n$$\nThis is greater than the $\\mathrm{K}_{\\mathrm{C}}$ of $3.60^{*} 10^{-2}$, hence the reaction would not be at equilibrium.\nThe reaction would have to move from right to left to establish equilibrium.",
    //     "calculations present": "Yes",
    //     "Subject": "Chemistry",
    //     "Topic Tag": ["Chemical Equilibrium", "Chemistry"]
    // },
    {
        "S/N": 11,
        "Has Preamble": "Yes",
        "Preamble Text": "Find the value of $n$ if",
        "Question": "$\\log _{8} n=1 / 2 p, \\log _{2}(4 n)=q$ and $q-p=3$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$\\mathbf{n}=8 \\quad\\left[\\mathrm{q}-\\mathrm{p}=\\log _{2}(4 \\mathrm{n})-(2 / 3) \\log _{2} \\mathrm{n}=3\\right.$,\n$2+\\log _{2} \\mathrm{n}-(2 / 3) \\log _{2} \\mathrm{n}=3,(1 / 3) \\log _{2} \\mathrm{n}=1, \\log _{2} \\mathrm{n}=3, \\mathrm{n}=2^{3}=8$ ]",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Opponent_Answer": 0,
        "Topic Tag": ["Logarithms", "Mathematics"]
    },
    {
        "S/N": 12,
        "Has Preamble": "Yes",
        "Preamble Text": "Find the value of $n$ if",
        "Question": "$2\\log _{9} n=p, \\log _{3}(9 n)=q$ and $p+q=6$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$\\mathbf{n}=9 \\quad\\left[\\mathrm{p}+\\mathrm{q}=2 \\log _{9} \\mathrm{n}+\\log _{3} 9+\\log _{3} \\mathrm{n}=6\\right.$,\n$\\log _{3} n+2+\\log _{3} n=6,2 \\log _{3} n=4, \\log _{3} n=2, n=3^{2}=9$ ]",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Logarithms", "Mathematics"]
    },

    {
        "S/N": 13,
        "Has Preamble": "Yes",
        "Preamble Text": "Assume $\\mathrm{x}$ and $\\mathrm{y}$ are positive real numbers. Express $\\mathrm{y}$ in terms of $\\mathrm{x}$ given",
        "Question": "$\\sin ^{-1} x=\\tan ^{-1} y$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$y=x / \\sqrt{ }\\left(1-x^{2}\\right) \\quad\\left[\\right.$ Let $\\tan ^{-1} y=a$, tana $=y, \\sin ^{-1} x=a$,\nhence $\\sin a=x$, tana $\\left.=x / \\sqrt{ }\\left(1-x^{2}\\right), y=x / \\sqrt{ }\\left(1-x^{2}\\right)\\right]$",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Opponent_Answer": 1,
        "Topic Tag": ["Inverse Trigonometric Functions", "Mathematics"]
    },
    {
        "S/N": 14,
        "Has Preamble": "Yes",
        "Preamble Text": "Assume $\\mathrm{x}$ and $\\mathrm{y}$ are positive real numbers. Express $\\mathrm{y}$ in terms of $\\mathrm{x}$ given",
        "Question": "$\\tan ^{-1} x=\\sin ^{-1} y$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$y=x / \\sqrt{ }\\left(x^{2}+1\\right)$\n$\\left[\\right.$ Let $\\sin ^{-1} y=a, \\sin a=y, \\tan ^{-1} x=a$, tana $=x, \\sin a=x / \\sqrt{ }\\left(1+x^{2}\\right)=y$ ]",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Inverse Trigonometric Functions", "Mathematics"]
    },

    {
        "S/N": 15,
        "Has Preamble": "Yes",
        "Preamble Text": "Evaluate the limit",
        "Question": "$\\operatorname{Lim}_{x \\rightarrow 9} \\frac{(x-9)}{(\\sqrt{x}-3)} \\quad$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "6\n$\\left[\\operatorname{Lim}_{x \\rightarrow 9} \\frac{(x-9)}{(\\sqrt{x}-3)}=\\operatorname{Lim}_{x \\rightarrow 9} \\frac{(x-9)(\\sqrt{x}+3)}{(x-9)}=\\operatorname{Lim}_{x \\rightarrow 9}(\\sqrt{x}+3)=3+3=6\\right]$",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Opponent_Answer": 1,
        "Topic Tag": ["Limits", "Mathematics"]
    },
    {
        "S/N": 16,
        "Has Preamble": "Yes",
        "Preamble Text": "Evaluate the limit",
        "Question": "$\\operatorname{Lim}_{x \\rightarrow 25} \\frac{(5-\\sqrt{x})}{(x-25)}$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$\\left.\\operatorname{Lim}_{x \\rightarrow 25} \\frac{(5-\\sqrt{x})}{(x-25)}=\\operatorname{Lim}_{x \\rightarrow 25} \\frac{(5-\\sqrt{x})}{(\\sqrt{x}-5)(\\sqrt{x}+5)}=\\operatorname{Lim}_{x \\rightarrow 25} \\frac{-1}{(\\sqrt{x}+5)}=\\frac{-1}{(5+5)}=\\frac{-1}{10}\\right]$",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Limits", "Mathematics"]
    },

    {
        "S/N": 17,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "A hydrogen atom moving away from a detector at $1.2 \\times 10^{8} \\mathrm{~m} \\mathrm{~s}^{-1}$ makes a transition from the first excited state to the ground state. Find the frequency of the radiation recorded by the detector.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$1.6 \\times 10^{15} \\mathrm{~Hz}$",
        "calculations present": "Yes",
        "Subject": "Physics",
        "Opponent_Answer": 0,
        "Topic Tag": ["Atomic Physics", "Physics"]
    },
    {
        "S/N": 18,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Find the frequency recorded by the detector if the hydrogen atom were moving towards the detector at $1.2 \\times 10^{8} \\mathrm{~m} \\mathrm{~s}^{-1}$ when it makes the transition from the first excited state to the ground state.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$3.8 \\times 10^{15} \\mathrm{~Hz}$",
        "calculations present": "Yes",
        "Subject": "Physics",
        "Topic Tag": ["Atomic Physics", "Physics"]
    },

    {
        "S/N": 19,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Find the speed of an electron at which its de Broglie wavelength is $5.0 \\mathrm{pm}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$1.3 \\times 10^{8} \\mathrm{~ms}^{-1}$",
        "calculations present": "Yes",
        "Subject": "Physics",
        "Opponent_Answer": 0,
        "Topic Tag": ["Quantum Mechanics", "Physics"]
    },
    {
        "S/N": 20,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Find the speed of an electron at which its de Broglie wavelength is $3.0 \\mathrm{pm}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$1.9 \\times 10^{8} \\mathrm{~ms}^{-1}$",
        "calculations present": "Yes",
        "Subject": "Physics",
        "Topic Tag": ["Quantum Mechanics", "Physics"]
    },

    {
        "S/N": 21,
        "Has Preamble": "Yes",
        "Preamble Text": "A particle of mass $3.3 \\times 10^{-27} \\mathrm{~kg}$ is trapped inside a cube of side $15 \\mathrm{pm}$ by infinitely high potential walls. The potential energy of the particle is everywhere zero inside the cube.",
        "Question": "What is the ground state energy of the particle?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$2.2 \\times 10^{-19} \\mathrm{~J}$",
        "calculations present": "Yes",
        "Subject": "Physics",
        "Opponent_Answer": 0,
        "Topic Tag": ["Quantum Mechanics", "Physics"]
    },
    {
        "S/N": 22,
        "Has Preamble": "Yes",
        "Preamble Text": "A particle of mass $3.3 \\times 10^{-27} \\mathrm{~kg}$ is trapped inside a cube of side $15 \\mathrm{pm}$ by infinitely high potential walls. The potential energy of the particle is everywhere zero inside the cube.",
        "Question": "What is the energy difference between the first excited state and the ground state of the particle?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$2.2 \\times 10^{-19} \\mathrm{~J}$\n$$\nE_{112}-E_{111}=\\frac{h^{2}}{8 m L^{2}} \\Delta\\left(n_{x}^{2}+n_{y}^{2}+n_{z}^{2}\\right)=\\frac{6-3}{8} \\times \\frac{\\left(6.63 \\times 10^{-34} \\mathrm{Js}\\right)^{2}}{3.3 \\times 10^{-27} \\mathrm{~kg} \\times\\left(15 \\times 10^{-12} \\mathrm{~m}\\right)^{2}}=2.2 \\times 10^{-19} \\mathrm{~J}\n$$",
        "calculations present": "Yes",
        "Subject": "Physics",
        "Topic Tag": ["Quantum Mechanics", "Physics"]
    },

]

export default contest_40_1