const contest_40_3 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Saponification is an industrial, alkaline hydrolysis of natural esters.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Opponent_Answer": 3,
        "Topic Tag": ["Saponification", "Organic Chemistry"]
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Saponification with caustic soda gives soft soap.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Saponification", "Organic Chemistry"]
    },

    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Cyclopentane and 3-methyl-1-butene are isomers.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Opponent_Answer": 3,
        "Topic Tag": ["Isomerism", "Organic Chemistry"]
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "$\\mathrm{Ca}^{2+}$ ions in solution do not form an insoluble sulphide when $\\mathrm{H}_{2} \\mathrm{~S}$ is bubbled through the solution.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Solubility", "Inorganic Chemistry"]
    },

    {
        "S/N": 5,
        "Has Preamble": "Yes",
        "Preamble Text": "For the logarithm of a positive number,",
        "Question": "the mantissa is positive,",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "TRUE",
        "Opponent_Answer": 3,
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Logarithms", "Mathematics"]
    },
    {
        "S/N": 6,
        "Has Preamble": "Yes",
        "Preamble Text": "For the logarithm of a positive number,",
        "Question": "the characteristic is positive",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Logarithms", "Mathematics"]
    },

    {
        "S/N": 7,
        "Has Preamble": "Yes",
        "Preamble Text": "Let functions $\\mathrm{f}$ and $\\mathrm{g}$ have domains $\\mathrm{A}$ and $\\mathrm{B}$ respectively.",
        "Question": "The function $(\\mathrm{f}+\\mathrm{g})(\\mathrm{x})=\\mathrm{f}(\\mathrm{x})+\\mathrm{g}(\\mathrm{x})$ has domain $\\mathrm{A} \\cup \\mathrm{B}$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "Opponent_Answer": 3,
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Functions", "Mathematics"]
    },
    {
        "S/N": 8,
        "Has Preamble": "Yes",
        "Preamble Text": "Let functions $\\mathrm{f}$ and $\\mathrm{g}$ have domains $\\mathrm{A}$ and $\\mathrm{B}$ respectively.",
        "Question": "The composite function $\\mathrm{f}(\\mathrm{g}(\\mathrm{x}))$ has domain $A \\cup B$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Functions", "Mathematics"]
    },

    {
        "S/N": 9,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "A charge $q$ outside a grounded conducting sphere at a distance $a$ from the center of the sphere which has a radius $R$ induces a total charge of $-q R / a$ on the sphere.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Physics",
        "Opponent_Answer": 3,
        "Topic Tag": ["Electrostatics", "Physics"]
    },
    {
        "S/N": 10,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "A charge $q$ inside a hollow grounded conducting sphere at a distance $a$ from the center of the sphere which has an inside radius $R$ induces a total charge of $-q R / a$ on the inside surface of the sphere.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Electrostatics", "Physics"]
    },

    {
        "S/N": 11,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The neutron is composed of one up and two down quarks and undergoes beta decay in which a proton is produced.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Physics",
        "Opponent_Answer": 3,
        "Topic Tag": ["Particle Physics", "Physics"]
    },
    {
        "S/N": 12,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "In the beta decay of a neutron, a down quark becomes an up quark with the release of an electron and an electron antineutrino, with the result that a proton is produced.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Particle Physics", "Physics"]
    },



]

export default contest_40_3