const contest_40_3 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The first ionization potential of magnesium is lower than that of aluminium.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Opponent_Answer": 2,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Ionization Energy", "Periodic Trends"]
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Oxygen and nitrogen both have higher first ionization energies than carbon, but oxygen has a lower ionisation energy than nitrogen.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Ionization Energy", "Periodic Trends"]
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "In the conversion of an alkane to an alkanol only one hydrogen atom is lost from the molecule.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "Opponent_Answer": 2,
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Organic Chemistry", "Hydrocarbons"]
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "In the conversion of an alkane into an alkanone only two hydrogen atoms are lost from the molecule",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Organic Chemistry", "Hydrocarbons"]
    },
    {
        "S/N": 5,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The electrostatic field is a conservative field.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "Opponent_Answer": 2,
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Electrostatics", "Physics"]
    },
    {
        "S/N": 6,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The electric field is a conservative field.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Electrostatics", "Physics"]
    },
    {
        "S/N": 7,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "A hydrogen atom in the 6h state can have an orbital angular momentum quantum number of 7 .",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "Opponent_Answer": 2,
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Electrostatics", "Physics"]
    },
    {
        "S/N": 8,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "A hydrogen atom in the $6 \\mathrm{~h}$ state can have an orbital angular momentum quantum number of 6.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Quantum Mechanics", "Atomic Structure"]
    },
    {
        "S/N": 9,
        "Has Preamble": "Yes",
        "Preamble Text": "Indicate whether the following are true or false with respect to the reasons why it is difficult to design a vaccine for viruses with high mutation rate such as the cold and flu viruses.",
        "Question": "Many protein fragments are represented that the immune system overreacts.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Opponent_Answer": 2,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Virology", "Immunology"]
    },
    {
        "S/N": 10,
        "Has Preamble": "Yes",
        "Preamble Text": "Indicate whether the following are true or false with respect to the reasons why it is difficult to design a vaccine for viruses with high mutation rate such as the cold and flu viruses.",
        "Question": "The vaccines tend to be unstable and deteriorate over time",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Virology", "Immunology"]
    },
    {
        "S/N": 11,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Analogous structures are structures found in different species that have similar functions resulting from natural selection",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "Opponent_Answer": 2,
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Evolution", "Comparative Anatomy"]
    },
    {
        "S/N": 12,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Homologous structures are structures found in different species that have similar anatomical forms, resulting from a common ancestor",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Evolution", "Comparative Anatomy"]
    },
    {
        "S/N": 13,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The rational number $5 / 8$ is less than the rational number $7 / 11$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "Opponent_Answer": 2,
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Rational Numbers", "Mathematics"]
    },
    {
        "S/N": 14,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The rational number $7 / 15$ is less than the rational number $8 / 17$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Rational Numbers", "Mathematics"]
    },
    {
        "S/N": 15,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "For a natural number $\\mathrm{n}$ to be divisible by 18 ,\nit is necessary that $\\mathrm{n}$ is divisible by 6",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "TRUE",
        "Opponent_Answer": 2,
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Divisibility", "Number Theory"]
    },
    {
        "S/N": 16,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "it is sufficient that $\\mathrm{n}$ is even and divisible by 9 .",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Divisibility", "Number Theory"]
    }
]

export default contest_40_3