const contest_40_4 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I owe my existence to J. J. Thomson.\nWe both deal with beams.\nWhile J.J. was interested in the negatively charged beam, I was interested in the positively charged beam.\nIn my operations positively charged units are first transformed into a beam.\nThe beam is made to travel through a magnetic field which separates the components according to mass-to-charge ratios.\nWho am I?",
        "clue1": "I owe my existence to J. J. Thomson",
        "clue2": "We both deal with beams",
        "clue3": "While J.J. was interested in the negatively charged beam, I was interested in the positively charged beam",
        "clue4": "In my operations positively charged units are first transformed into a beam",
        "clue5": "The beam is made to travel through a magnetic field which separates the components according to mass-to-charge ratios.Who am I?",
        "clue_nums": 5,
        "Prempeh_Answer": 0,
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Mass Spectrometry or Mass Spectrometer",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am a particle with mass.\nI am deflected by an inhomogeneous magnetic field, which can split an unpolarized beam of me into two beams.\nI am composed of three spin- $1 / 2$ fractional charge particles.\nIn the free state, I decay with a half-life of about 10 minutes and 11 seconds.\nI am the particle that distinguishes the deuteron from the proton.\nWho am I?",
        "Question has figure": "No",
        "clue1": "I am a particle with mass",
        "clue2": "I am deflected by an inhomogeneous magnetic field, which can split an unpolarized beam of me into two beams.",
        "clue3": "I am composed of three spin- $1 / 2$ fractional charge particles.",
        "clue4": "In the free state, I decay with a half-life ",
        "clue_nums": 4,
        "Prempeh_Answer": 3,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Neutron",
        "calculations present": "No",
        "Subject": "Physics"
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am a major operation or process in Statistics.\nLike most statistical operations, I start with the collection of data.\nIn my case this is usually at the national level.\nI involve collection of information from all individuals in a population.\nIn a lot of jurisdictions as in Ghana, I occur every ten years.\nWe have had one in Ghana this year.\nWho am I?",
        "Question has figure": "No",
        "clue1": "I am a major operation or process in Statistics.",
        "clue2": "Like most statistical operations, I start with the collection of data",
        "clue3": "In my case this is usually at the national level.",
        "clue4": "I involve collection of information from all individuals in a population",
        "clue5": "In a lot of jurisdictions as in Ghana, I occur every ten years",
        "clue6": "nWe have had one in Ghana this year. Who am I?",
        "clue_nums": 6,
        "Prempeh_Answer": 0,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "POPULATION CENSUS (accept CENSUS)",
        "calculations present": "No",
        "Subject": "Mathematics"
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "We are a wide variety of organisms, ranging from animals to plants and even microorganisms.\nWhat constitutes us is not clear and varies widely between countries, international bodies and other communities\nThere has been much debate over us and the potential benefits and risks associated with us.\nThough the main concern with us is the lack of testing, we are seen as beneficial by many, especially people in the agricultural industry.\nWe are organisms whose genetic materials have been altered using genetic engineering techniques.\nWHO ARE WE?",
        "clue1": "We are a wide variety of organisms, ranging from animals to plants and even microorganisms.",
        "clue2": "What constitutes us is not clear and varies widely between countries, international bodies and other communities",
        "clue3": "There has been much debate over us and the potential benefits and risks associated with us.",
        "clue4": "Though the main concern with us is the lack of testing, we are seen as beneficial by many, especially people in the agricultural industry",
        "clue5": "We are organisms whose genetic materials have been altered ",
        "clue_nums": 5,
        "Prempeh_Answer": 3,
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Genetically modified organisms/ Genetically engineered organisms",
        "calculations present": "No",
        "Subject": "Biology"
    }
]

export default contest_40_4