import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { AuthProvider } from "@/app/context/AuthContext";
import WithAuth from "../../middleware/ProtectedRoute"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AddStudentLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <WithAuth>
                <AuthProvider>
                    <body className={inter.className}>{children}</body>
                </AuthProvider>
            </WithAuth>
        </html>

    );
}
