const contest_2_3 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "1-Hexanol and 2-hexanol both belong to the same homologous series.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Homologous Series", "Organic Chemistry"]
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "2-Hexanol and 3-hexanol are position isomers.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Isomerism", "Organic Chemistry"]
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Both 2-Hexanol and 3-Hexanol are optically active.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Optical Activity", "Organic Chemistry"]
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "In a chemical reaction energy is evolved when bonds in the products are being formed.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Bond Energy", "Chemical Reactions"]
    },
    {
        "S/N": 5,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "In an exothermic reaction the products are more thermodynamically stable than the reactants.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Thermodynamics", "Chemical Reactions"]
    },
    {
        "S/N": 6,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Exothermic reactions usually have lower activation energies than endothermic reactions.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False.",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Activation Energy", "Thermodynamics"]
    },
    {
        "S/N": 7,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Total linear momentum is conserved whenever net force vanishes.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Momentum", "Physics"]
    },
    {
        "S/N": 8,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "In the collision between two freely moving balls, only the component of linear momentum along the line of centers is conserved.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Collisions", "Physics"]
    },
    {
        "S/N": 9,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "In an inelastic collision, kinetic energy is not conserved so linear momentum is also not conserved because kinetic energy depends on the square of linear momentum",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Inelastic Collisions", "Physics"]
    },
    {
        "S/N": 10,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "A blackbody emits as well as absorbs radiation.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Blackbody Radiation", "Physics"]
    },
    {
        "S/N": 11,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "A blackbody at a given temperature can appear hot only if it emits more radiation than it absorbs.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Blackbody Radiation", "Physics"]
    },
    {
        "S/N": 12,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "An object looks black to the human eye because it does not emit any radiation.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics",
        "Topic Tag": ["Blackbody Radiation", "Physics"]
    },
    {
        "S/N": 13,
        "Has Preamble": "Yes",
        "Preamble Text": "State whether the following statements are true or false with respect to respiration.",
        "Question": "Oxygen reacts with an inorganic compound to produce carbon dioxide, water, and energy.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Aerobic Respiration", "Cellular Respiration"]
    },
    {
        "S/N": 14,
        "Has Preamble": "Yes",
        "Preamble Text": "State whether the following statements are true or false with respect to respiration.",
        "Question": "It is an Intermediate process",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Cellular Respiration", "Metabolic Processes"]
    },
    {
        "S/N": 15,
        "Has Preamble": "Yes",
        "Preamble Text": "State whether the following statements are true or false with respect to respiration.",
        "Question": "It is an anabolic process",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Anabolic Processes", "Metabolism"]
    },
    {
        "S/N": 16,
        "Has Preamble": "Yes",
        "Preamble Text": "State whether the following are true or false with respect to the functions of hormones",
        "Question": "Plays a role in reproduction and sexual differentiation",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Reproductive Hormones", "Endocrine System"]
    },
    {
        "S/N": 17,
        "Has Preamble": "Yes",
        "Preamble Text": "State whether the following are true or false with respect to the functions of hormones",
        "Question": "Maintenance of internal environment of animals",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Homeostasis", "Endocrine System"]

    },
    {
        "S/N": 18,
        "Has Preamble": "Yes",
        "Preamble Text": "State whether the following are true or false with respect to the functions of hormones",
        "Question": "Maintenance of body temperature of mammals",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Thermoregulation", "Endocrine System"]
    },
    {
        "S/N": 19,
        "Has Preamble": "Yes",
        "Preamble Text": "Given that $f(x)=(x-4)\\left(x^{2}-8 x+15\\right)$",
        "Question": "$f(x)=0$ when $x=-4$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Roots of Functions", "Polynomial Functions"]
    },
    {
        "S/N": 20,
        "Has Preamble": "Yes",
        "Preamble Text": "Given that $f(x)=(x-4)\\left(x^{2}-8 x+15\\right)$",
        "Question": "$f(x)=60$ when $x=8$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Function Evaluation", "Polynomial Functions"]
    },
    {
        "S/N": 21,
        "Has Preamble": "Yes",
        "Preamble Text": "Given that $f(x)=(x-4)\\left(x^{2}-8 x+15\\right)$",
        "Question": "$f(x)=1$ when $x=5$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Function Evaluation", "Polynomial Functions"]
    },
    {
        "S/N": 22,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "$-\\left(9-x^{2}\\right)=(3+x)(x-3)$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Factoring Equations", "Algebra"]
    },
    {
        "S/N": 23,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "$-2 x /-(6-x)=2 x /(x-6)$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Rational Expressions", "Algebra"]
    },
    {
        "S/N": 24,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "$(2 x+5) /\\left(16-x^{2}\\right)=(-2 x-5) /\\left(x^{2}-16\\right)$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "Yes",
        "Subject": "Mathematics",
        "Topic Tag": ["Rational Expressions", "Algebra"]
    }
]

export default contest_2_3