const contest_1_3 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Dimerization of ethanoic acid through hydrogen bonding is less pronounced in aqueous solutions than in non-polar solvents.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "T. $\\quad$ (It is more pronounced in non-polar solvents.)",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Ethanoic acid exhibits the same molar units in the vapour phase as in an aqueous solution.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "F. (In the vapour phase there is extensive dimerization)",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "3-Methylbutanoic acid will have a larger pKa than 3-chlorobutanoic acid.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "T.",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The addition of a catalyst to a reversible reaction whose forward reaction is endothermic, increases the rate of the forward reaction more than that of the backward reaction.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$F$.",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 5,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Increasing the initial concentration of a reactant three-fold in a second order reaction will increase the initial rate eight times.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "F. It will increase it by a factor of 9 .",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 6,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "In the catalytic reduction of alkenes using a transition metal, the greater the surface area, the greater the rate of the reaction.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "T. (Heterogenous catalysis is a surface action.)",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 7,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Every triangle has a center of symmetry.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "calculations present": "No",
        "Subject": "Mathematics"
    },
    {
        "S/N": 8,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "An isosceles triangle has a center of symmetry.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "calculations present": "No",
        "Subject": "Mathematics"
    },
    {
        "S/N": 9,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "An equilateral triangle has a center of symmetry.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "calculations present": "No",
        "Subject": "Mathematics"
    },
    {
        "S/N": 10,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "$y=2 \\sin x$ has a maximum value at $x=\\pi$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "calculations present": "No",
        "Subject": "Mathematics"
    },
    {
        "S/N": 11,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "$y=3 \\cos x$ has a maximum value at $x=\\pi$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "calculations present": "No",
        "Subject": "Mathematics"
    },
    {
        "S/N": 12,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "$y=\\tan x$ has a maximum value at $x=\\pi$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "FALSE",
        "calculations present": "No",
        "Subject": "Mathematics"
    },
    {
        "S/N": 13,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The fibrous root system is assumed to have evolved before the taproot system in evolutionary history.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 14,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Plants with fibrous root systems usually have leaves with parallel venation.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 15,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The fibrous root system begins as a tap root from the radicle, but as the plant grows, the radicle degenerates, and no primary root is seen",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 16,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The complete process of spermatogenesis occurs in different stages that take place in different structures within the male reproductive system.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 17,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Spermatogenesis in males start before the birth of the male child",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 18,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Spermatogenesis is a continuous process that begins with puberty and continuous until death.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 19,
        "Has Preamble": "Yes",
        "Preamble Text": "A $1 \\mu \\mathrm{F}$, a $2 \\mu \\mathrm{F}$, and a $3 \\mu \\mathrm{F}$ capacitor are connected in series.",
        "Question": "The equivalent capacitance of the series network equals $6 \\mu \\mathrm{F}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics"
    },
    {
        "S/N": 20,
        "Has Preamble": "Yes",
        "Preamble Text": "A $1 \\mu \\mathrm{F}$, a $2 \\mu \\mathrm{F}$, and a $3 \\mu \\mathrm{F}$ capacitor are connected in series.",
        "Question": "The equivalent capacitance of the series network is less than $6 \\mu \\mathrm{F}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Physics"
    },
    {
        "S/N": 21,
        "Has Preamble": "Yes",
        "Preamble Text": "A $1 \\mu \\mathrm{F}$, a $2 \\mu \\mathrm{F}$, and a $3 \\mu \\mathrm{F}$ capacitor are connected in series.",
        "Question": "The equivalent capacitance of the series network is less than $3 \\mu \\mathrm{F}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Physics"
    },
    {
        "S/N": 22,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The activity of a radioactive sample decreases as the temperature of the sample is increased.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics"
    },
    {
        "S/N": 23,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The activity of a radioactive sample increases as the pressure on the sample is increased.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics"
    },
    {
        "S/N": 24,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "The activity of a radioactive sample decreases as the temperature of the sample is decreased.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False",
        "calculations present": "No",
        "Subject": "Physics"
    }
]

export default contest_1_3