const contest_3_4 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am synthesized by an addition reaction.\nThe reaction may be initiated with a cation or anion or even a free radical.\nAlmost always the reaction is carried out under pressure.\nMy giant molecule appears to be made up of many repeated units.\nMy backbone is made up of a chain of $\\mathrm{sp}^{3}$-carbons with a methyl group on alternating carbons.\nWho am I?",
        "Question has figure": "No",
        "clue1": "I am synthesized by an addition reaction",
        "clue2": "The reaction may be initiated with a cation or anion or even a free radical",
        "clue3": "Almost always the reaction is carried out under pressure",
        "clue4": "My giant molecule appears to be made up of many repeated units",
        "clue5": "My backbone consists of a chain of s p 3 carbons with a methyl group attached to every other carbons. Who am I?",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Polypropene or Polypropylene",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am a dynamical quantity.\nI am a vector quantity.\nMy SI unit is the $\\mathrm{kg} \\mathrm{m} \\mathrm{s^{-1}}$ or the $\\mathrm{N} \\mathrm{s}$.\nI equal the product of a scalar and a vector quantity.\nFor slowly moving objects, I am calculated as the product of mass and velocity.\nWho am I?",
        "Question has figure": "No",
        "clue1": "I am a dynamical quantity.",
        "clue2": "I am a vector quantity",
        "clue3": "My SI unit is the $\\mathrm{kg} \\mathrm{m} \\mathrm{s^{-1}}$ or the $\\mathrm{N} \\mathrm{s}$",
        "clue4": "I equal the product of a scalar and a vector quantity",
        "clue5": "For slowly moving objects, I am calculated as the product of mass and velocity.\nWho am I?",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Linear momentum",
        "calculations present": "No",
        "Subject": "Physics"
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "We are microscopic channels which traverse the cell walls of plant cells and some algal cells\nWe evolved independently in several lineages\nThere are two forms of us, primary which are formed during cell division, and secondary, which can form between mature cells\nWe are formed when fractions of the endoplasmic reticulum are trapped across the middle lamella as new cell walls are synthesized between two newly divided plant cells.\nWe are tiny passages or channels that allow the transfer of materials and communication between different cells.\nWHO ARE WE?",
        "Question has figure": "No",
        "clue1": "We are microscopic channels which traverse the cell walls of plant cells and some algal cells",
        "clue2": "We evolved independently in several lineages",
        "clue3": "There are two forms of us, primary which are formed during cell division, and secondary, which can form between mature cells",
        "clue4": "We are formed when fractions of the endoplasmic reticulum are trapped across the middle lamella as new cell walls are synthesized between two newly divided plant cells",
        "clue5": "We are tiny passages or channels that allow the transfer of materials and communication between different cells.\nWho Are We?",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Plasmodesmata",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am an operation.\nI am a binary operation.\nI am not associative.\nNeither am I commutative.\nI am one of the 4 basic binary operations on the set of real numbers.\nI am definitely not division.\nWho am I?",
        "Question has figure": "No",
        "clue1": "I am an operation",
        "clue2": "I am a binary operation",
        "clue3": "I am not associative. Neither am I commutative",
        "clue4": "I am one of the 4 basic binary operations on the set of real numbers",
        "clue5": "I am definitely not division.\nWho am I?",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "SUBTRACTION",
        "calculations present": "No",
        "Subject": "Mathematics"
    }
]

export default contest_3_4