const contest_1_4 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am built to take unexpected shocks.\nI could also be seen as being able to stop two large states from open confrontations.\nBut I am not a state but a reagent.\nI have the characteristic property to stop unwanted change.\nI am in my elements if the expected change is due to addition of small amounts of acids or bases.\nWho am I?",
        "Question has figure": "No",
        'clue1': "I am built to take unexpected shocks",
        "clue2": "I could also be seen as being able to stop two large states from open confrontations",
        "clue3": "But I am not a state but a reagent",
        "clue4": "I have the characteristic property to stop unwanted change",
        "clue5": "I am in my elements if the expected change is due to addition of small amounts of acids or bases.\nWho am I?",
        "clue_nums": 5,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Buffer",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Buffer Solutions", "Acid-Base Chemistry"]
    },
    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am a thermodynamic process.\nI am accompanied by changes in internal energy whenever work is involved with me.\nFor reversible processes, I am equivalent to an adiabatic process.\nI occur with no change in a measure of the degree of disorder in a system.\nI am the thermodynamic process in which entropy remains constant.\nWho am I?",
        "Question has figure": "No",
        "clue1": "I am a thermodynamic process.",
        "clue2": "I am accompanied by changes in internal energy whenever work is involved with me.",
        "clue3": "For reversible processes, I am equivalent to an adiabatic process.",
        "clue4": "I occur with no change in a measure of the degree of disorder in a system",
        "clue5": "I am the thermodynamic process in which entropy remains constant.\nWho am I?",
        "clue_nums": 5,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Isentropic process",
        "calculations present": "No",
        "Subject": "Chemistry",
        "Topic Tag": ["Thermodynamic Processes", "Isentropic Processes"]
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am a power.\nI am an index\nI am the power a number should be raised to obtain another number\nIf $a^{x}=y$, then $x=\\log _{a} y$\nI have rules unto myself such as the product rule.\nWho am I?",
        "Question has figure": "No",
        "clue1": "I am a power",
        "clue2": "I am an index",
        "clue3": "I am the power a number should be raised to obtain another number",
        "clue4": "If $a^{x}=y$, then $x=\\log _{a} y$",
        "clue5": "I have rules unto myself such as the product rule.Who am I",
        "clue_nums": 5,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "LOGARITHM",
        "calculations present": "No",
        "Subject": "Mathematics",
        "Topic Tag": ["Logarithms", "Algebra"]
    },
    {
        "S/N": 4,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "I am one of the many unique organelles in a cell,\nI am generally considered to have originated from endosymbiotic cyanobacteria.\nIn this respect, I am similar to mitochondria, but am found only in plants and Protista\nBoth of us are surrounded by a double celled composite membrane with an intermembrane space\nLike mitochondria, I contain my own DNA, which is thought to be inherited from my ancestor",
        "Question has figure": "No",
        "clue1": "I am one of the many unique organelles in a cell",
        "clue2": "I am generally considered to have originated from endosymbiotic cyanobacteria.",
        "clue3": "In this respect, I am similar to mitochondria, but am found only in plants and Protista",
        "clue4": "Both of us are surrounded by a double celled composite membrane with an intermembrane space",
        "clue5": "Like mitochondria, I contain my own DNA, which is thought to be inherited from my ancestor. Who am I?",
        "clue_nums": 5,
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Chloroplast",
        "calculations present": "No",
        "Subject": "Biology",
        "Topic Tag": ["Cell Biology", "Organelles", "Chloroplast"]

    }
]

export default contest_1_4