const contest_2_3 = [
    {
        "S/N": 1,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Molten magnesium chloride is a good conductor of electricity.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Chemistry"
    },

    {
        "S/N": 2,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Solid sodium chloride consists of a giant lattice.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "True",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 3,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Solid Boron chloride is a giant polymer.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "False.",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    // {
    //     "S/N": 4,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "The first ionization energy of oxygen is higher than that of nitrogen.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "$\\mathrm{F}$.",
    //     "calculations present": "No",
    //     "Subject": "Chemistry"
    // },
    // {
    //     "S/N": 5,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "In Period 2 of the Periodic Table neon has the highest first ionization energy",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "T.",
    //     "calculations present": "No",
    //     "Subject": "Chemistry"
    // },
    // {
    //     "S/N": 6,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "Of the elements, magnesium, aluminium and silicon, aluminium has the lowest first ionization energy.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "T.",
    //     "calculations present": "No",
    //     "Subject": "Chemistry"
    // },
    // {
    //     "S/N": 7,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "$3>\\sqrt{8}$",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "TRUE",
    //     "calculations present": "No",
    //     "Subject": "Mathematics"
    // },
    // {
    //     "S/N": 8,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "$2 \\sqrt{ } 7>3 \\sqrt{ } 3$",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "TRUE",
    //     "calculations present": "No",
    //     "Subject": "Mathematics"
    // },
    // {
    //     "S/N": 9,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "$3 \\sqrt{5}>4 \\sqrt{ } 3$",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "FALSE",
    //     "calculations present": "No",
    //     "Subject": "Mathematics"
    // },
    // {
    //     "S/N": 10,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "If the sum of the interior angles of a triangle is $300^{\\circ}$, then it is a rectangle.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "TRUE",
    //     "calculations present": "No",
    //     "Subject": "Mathematics"
    // },
    // {
    //     "S/N": 11,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "If $3+6=10$, then $3 \\times 6=15$",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "TRUE",
    //     "calculations present": "No",
    //     "Subject": "Mathematics"
    // },
    // {
    //     "S/N": 12,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "If the interior angle of a rectangle measures $120^{\\circ}$, then it is a pentagon.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "TRUE",
    //     "calculations present": "No",
    //     "Subject": "Mathematics"
    // },
    // {
    //     "S/N": 13,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "Amphibians have a narrower range of color spectrum whereas reptiles have a wider range of the color spectrum.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "True",
    //     "calculations present": "No",
    //     "Subject": "Biology"
    // },
    // {
    //     "S/N": 14,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "Reptiles tend to secrete highly toxic substances on their skin for protection against predators whereas amphibians have hard scales all over the skin for protection.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "False",
    //     "calculations present": "No",
    //     "Subject": "Biology"
    // },
    // {
    //     "S/N": 15,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "Amphibians undergo metamorphosis whereas reptiles do not experience any larval stages.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "True",
    //     "calculations present": "No",
    //     "Subject": "Biology"
    // },
    // {
    //     "S/N": 16,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "Mosses, algae, lichens and other lower organisms adapted to dry habitats always have cells with large volume",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "False",
    //     "calculations present": "No",
    //     "Subject": "Biology"
    // },
    // {
    //     "S/N": 17,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "Buds of higher plants are completely devoid of vacuoles and are quite resistant to drought.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "True",
    //     "calculations present": "No",
    //     "Subject": "Biology"
    // },
    // {
    //     "S/N": 18,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "The characteristics of the cells of xerophytic plants are that they are relatively small in size with small vacuoles.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "True",
    //     "calculations present": "No",
    //     "Subject": "Biology"
    // },
    // {
    //     "S/N": 19,
    //     "Has Preamble": "Yes",
    //     "Preamble Text": "Suppose a uranium fission reactor were operated without a moderator.",
    //     "Question": "Excessive heat will be generated.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "False",
    //     "calculations present": "No",
    //     "Subject": "Chemistry, Physics"
    // },
    // {
    //     "S/N": 20,
    //     "Has Preamble": "Yes",
    //     "Preamble Text": "Suppose a uranium fission reactor were operated without a moderator.",
    //     "Question": "Meltdown of the reactor will occur.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "False",
    //     "calculations present": "No",
    //     "Subject": "Chemistry, Physics"
    // },
    // {
    //     "S/N": 21,
    //     "Has Preamble": "Yes",
    //     "Preamble Text": "Suppose a uranium fission reactor were operated without a moderator.",
    //     "Question": "The fuel rods will become enriched in uranium-235.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "False",
    //     "calculations present": "No",
    //     "Subject": "Chemistry, Physics"
    // },
    // {
    //     "S/N": 22,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "The impulse of a force is a vector quantity.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "True",
    //     "calculations present": "No",
    //     "Subject": "Physics"
    // },
    // {
    //     "S/N": 23,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "The impulse of a force and the work of a force have dimensionally equivalent units.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "False",
    //     "calculations present": "No",
    //     "Subject": "Physics"
    // },
    // {
    //     "S/N": 24,
    //     "Has Preamble": "No",
    //     "Preamble Text": null,
    //     "Question": "The impulse of a force and linear momentum have dimensionally equivalent units.",
    //     "Question has figure": "No",
    //     "Question figure name": null,
    //     "Answer has figure": "No",
    //     "Answer figure name": null,
    //     "Answer": "True",
    //     "calculations present": "No",
    //     "Subject": "Physics"
    // }
]

export default contest_2_3