const contest_2_1 = [
    {
        "S/N": 1,
        "Has Preamble": "Yes",
        "Preamble Text": "Find the degree measures of the interior angles of a triangle if",
        "Question": "the exterior angles are in the ratio $3: 4: 5$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$90^{\\circ}, 60^{\\circ}$,\n$30^{\\circ}$\n$[3 x+4 x+5 x=12 x=360, x=30$, exterior angles are $90,120,150$, interior angles are $180-90=90,180-120=60,180-150=30]$",
        "calculations present": "Yes",
        "Subject": "Mathematics"
    },
    {
        "S/N": 2,
        "Has Preamble": "Yes",
        "Preamble Text": "Find the degree measures of the interior angles of a triangle if",
        "Question": "the exterior angles are in the ratio 11: 12: 13",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$\\mathbf{7 0}^{\\circ}, \\mathbf{6 0}^{\\circ}, \\mathbf{5 0}^{\\circ}$\n$[11 x+12 x+13 x=36 x=360, x=10$, exterior angles are $110,120,130$, interior angles are $180-110=70,180-120=60,180-130=50]$",
        "calculations present": "Yes",
        "Subject": "Mathematics"
    },
    {
        "S/N": 3,
        "Has Preamble": "Yes",
        "Preamble Text": "Find the degree measures of the interior angles of a triangle if",
        "Question": "the exterior angles are in the ratio 5: 6:7",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$\\mathbf{8 0}^{\\circ}, \\mathbf{6 0}^{\\circ}, \\mathbf{4 0}^{\\circ}$ $[5 x+6 x+7 x=18 x=360, x=20$, exterior angles are $100,120,140$, interior angles are $180-100=80,180-120=60,180-140=40]$",
        "calculations present": "Yes",
        "Subject": "Mathematics"
    },
    {
        "S/N": 4,
        "Has Preamble": "Yes",
        "Preamble Text": "Find the values of $A, B, C$ such that",
        "Question": "$9 x^{2}+12 x+A=(3 x+B)^{2}$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$A=4, B=2$\n$\\left[9 x^{2}+12 x+A=9 x^{2}+6 B x+B^{2}, 12=6 B, B=2, A=B^{2}=2^{2}=4\\right]$",
        "calculations present": "Yes",
        "Subject": "Mathematics"
    },
    {
        "S/N": 5,
        "Has Preamble": "Yes",
        "Preamble Text": "Find the values of $A, B, C$ such that",
        "Question": "$4 x^{2}+16 x+25=A(x+B)^{2}+C$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$A=4, B=2, C=9$\n$\\left[4 x^{2}+16 x+25=4\\left(x^{2}+4 x\\right)+25=4(x+2)^{2}+25-16, A=4, B=2, C=\\right.$ 9]",
        "calculations present": "Yes",
        "Subject": "Mathematics"
    },
    {
        "S/N": 6,
        "Has Preamble": "Yes",
        "Preamble Text": "Find the values of $A, B, C$ such that",
        "Question": "$5 x^{2}-30 x-6=A(x+B)^{2}+C$",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$A=5, B=-3, C=-51$\n$\\left[5\\left(x^{2}-6 x\\right)-6=5(x-3)^{2}-45-6=A(x+B)^{2}+C, A=5, B=-3, C=-51\\right]$",
        "calculations present": "Yes",
        "Subject": "Mathematics"
    },
    {
        "S/N": 7,
        "Has Preamble": "Yes",
        "Preamble Text": "Indicate whether the following are anabolic or catabolic processes",
        "Question": "Photosynthesis",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Anabolic",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 8,
        "Has Preamble": "Yes",
        "Preamble Text": "Indicate whether the following are anabolic or catabolic processes",
        "Question": "Excretion",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Catabolic",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 9,
        "Has Preamble": "Yes",
        "Preamble Text": "Indicate whether the following are anabolic or catabolic processes",
        "Question": "Cellular respiration",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Catabolic",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 10,
        "Has Preamble": "Yes",
        "Preamble Text": "Describe hormones with respect to the following",
        "Question": "Site of action",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Hormones perform activity at some distance away from the site of origin.",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 11,
        "Has Preamble": "Yes",
        "Preamble Text": "Describe hormones with respect to the following",
        "Question": "Fate of their chemical composition after reactions",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Their chemical composition changes after reaction",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 12,
        "Has Preamble": "Yes",
        "Preamble Text": "Describe hormones with respect to the following",
        "Question": "Type of glands that synthesize and secrete them",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Hormones are synthesized and secreted by endocrine glands.",
        "calculations present": "No",
        "Subject": "Biology"
    },
    {
        "S/N": 13,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Which element has atoms with bigger atomic radius, silicon, or aluminium?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Aluminium",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 14,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Which element is relatively more electropositive, sulphur or selenium?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Selenium",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 15,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Which element has the higher first ionization energy, hydrogen, or helium?",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "Helium",
        "calculations present": "No",
        "Subject": "Chemistry"
    },
    {
        "S/N": 16,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "If the enthalpies of formation in $\\mathrm{kJmol}^{-1}$ of 1-pentyne, 1-pentene and pentane are $+145,-21.0$, and -147 respectively, calculate the enthalpy of hydrogenation of i) 1pentyne to 1-pentene and ii) 1-pentene to pentane. Indicate which reaction is thermodynamically more favourable.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "1-Pentyne $\\rightarrow$ 1-pentene\n$\\Delta r=\\Sigma \\Delta \\mathrm{H}_{\\text {products }}-\\Sigma \\Delta \\mathrm{H}_{\\text {reactants }}=-21.0-(+145)=-166 \\mathrm{~kJ}$\n1-Pentene $\\rightarrow$ pentane\n$\\Delta r=\\Sigma \\Delta \\mathrm{H}_{\\text {products }}-\\Sigma \\Delta \\mathrm{H}_{\\text {reactants }}=-147-(-21.0)=-126 \\mathrm{~kJ}$\nThe reduction from 1-pentyne to 1-pentene is thermodynamically more favourable.",
        "calculations present": "Yes",
        "Subject": "Chemistry"
    },
    {
        "S/N": 17,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "If the enthalpies of formation in $\\mathrm{kJmol}^{-1}$ of 2-pentyne, cis-2-pentene and trans-2pentene are $+129,-28.1$ and -31.9 respectively, calculate the enthalpy change for the reduction 2-pentyne to i) cis-2-pentene and ii) trans-2-pentene. Indicate which reaction is thermodynamically more favourable and give the reason for that relative order.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "2-Pentyne $\\rightarrow$ cis-2-pentene\n$$\n\\begin{aligned}\n& \\Delta r=-28.1-(+129) \\quad=-157 \\mathrm{~kJ} \\\\\n& \\text { 2-Pentyne } \\rightarrow \\text { trans-2-pentene } \\\\\n& \\Delta r \\quad-31.9-(+129) \\quad-161 \\mathrm{~kJ}\n\\end{aligned}\n$$\nReduction to the trans compound is thermodynamically more favourable.\nReason: The trans compound is more stable/has lower internal energy",
        "calculations present": "Yes",
        "Subject": "Chemistry"
    },
    {
        "S/N": 18,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "If the enthalpies of formation in $\\mathrm{kJmol}^{-1}$ of cis-2-pentene, trans-2-pentene and pentane are $-28.1,-31.9$ and -147 respectively, calculate the enthalpy change for the reduction\ni) cis-2-pentene to pentane and ii) trans-2-pentene to pentane. Indicate which reaction is thermodynamically more favourable and give the reason for that relative order.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "cis-2-Pentene $\\rightarrow$ pentane\n$\\begin{array}{llll}\\Delta r \\quad-147- & (-28.1) & =-119 \\mathrm{~kJ} \\\\ \\text { trans-2-Pentene } \\rightarrow & \\text { pentane } \\\\ \\Delta r \\quad-147-(-31.9) & =-115 \\mathrm{~kJ}\\end{array}$\nReduction of the cis compound is thermodynamically more favourable.\nReason: The cis compound is less stable/has higher internal energy.",
        "calculations present": "Yes",
        "Subject": "Chemistry"
    },
    {
        "S/N": 19,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Find the kinetic energy of a uniform sphere of mass $32 \\mathrm{~kg}$ and radius $0.10 \\mathrm{~m}$ rotating about a fixed axis passing through its center at an angular frequency of $5.0 \\mathrm{rad} \\mathrm{s}^{-1}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$1.6 \\mathrm{~J}$",
        "calculations present": "Yes",
        "Subject": "Physics"
    },
    {
        "S/N": 20,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Find the kinetic energy of the uniform sphere of mass $32 \\mathrm{~kg}$ and radius $0.10 \\mathrm{~m}$ when it rotates about the fixed axis passing through its center at an angular frequency of $2.5 \\mathrm{rad} \\mathrm{s}^{-1}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$0.40 \\mathrm{~J}$",
        "calculations present": "Yes",
        "Subject": "Physics"
    },
    {
        "S/N": 21,
        "Has Preamble": "No",
        "Preamble Text": null,
        "Question": "Find the kinetic energy of a uniform sphere of mass $25 \\mathrm{~kg}$ and radius $0.20 \\mathrm{~m}$ rotating about a fixed axis passing through its center at an angular frequency of $3.0 \\mathrm{rad} \\mathrm{s}^{-1}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$1.8 \\mathrm{~J}$",
        "calculations present": "Yes",
        "Subject": "Physics"
    },
    {
        "S/N": 22,
        "Has Preamble": "Yes",
        "Preamble Text": "A fixed quantity of an ideal gas undergoes an isothermal process.",
        "Question": "Find the final pressure of the gas if its initial pressure is $200 \\mathrm{kPa}$, its initial volume is $15 \\mathrm{dm}^{3}$, and its final volume is $25 \\mathrm{dm}^{3}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$120 \\mathrm{kPa}$",
        "calculations present": "Yes",
        "Subject": "Physics"
    },
    {
        "S/N": 23,
        "Has Preamble": "Yes",
        "Preamble Text": "A fixed quantity of an ideal gas undergoes an isothermal process.",
        "Question": "Find the final volume of the gas if its initial pressure is $220 \\mathrm{kPa}$, its final pressure is $120 \\mathrm{kPa}$, and its initial volume is $3.6 \\mathrm{~m}^{3}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$6.6 m^{3}$",
        "calculations present": "Yes",
        "Subject": "Physics"
    },
    {
        "S/N": 24,
        "Has Preamble": "Yes",
        "Preamble Text": "A fixed quantity of an ideal gas undergoes an isothermal process.",
        "Question": "Find the initial pressure of the gas if its final pressure is $400 \\mathrm{kPa}$, its initial volume is $10 \\mathrm{dm}^{3}$, and its final volume is $25 \\mathrm{dm}^{3}$.",
        "Question has figure": "No",
        "Question figure name": null,
        "Answer has figure": "No",
        "Answer figure name": null,
        "Answer": "$1000 \\mathrm{kPa}$",
        "calculations present": "Yes",
        "Subject": "Physics"
    }
]

export default contest_2_1